# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import steelbeam_pb2 as proto_dot_steelbeam__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/steelbeam_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SteelBeamServiceStub(object):
    """SteelBeam service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBeams = channel.unary_unary(
                '/steelbeam.SteelBeamService/GetBeams',
                request_serializer=proto_dot_steelbeam__pb2.GetBeamsRequest.SerializeToString,
                response_deserializer=proto_dot_steelbeam__pb2.GetBeamsResponse.FromString,
                _registered_method=True)
        self.GetBeam = channel.unary_unary(
                '/steelbeam.SteelBeamService/GetBeam',
                request_serializer=proto_dot_steelbeam__pb2.GetBeamRequest.SerializeToString,
                response_deserializer=proto_dot_steelbeam__pb2.GetBeamResponse.FromString,
                _registered_method=True)
        self.CreateBeam = channel.unary_unary(
                '/steelbeam.SteelBeamService/CreateBeam',
                request_serializer=proto_dot_steelbeam__pb2.CreateBeamRequest.SerializeToString,
                response_deserializer=proto_dot_steelbeam__pb2.CreateBeamResponse.FromString,
                _registered_method=True)
        self.GetStockStatus = channel.unary_unary(
                '/steelbeam.SteelBeamService/GetStockStatus',
                request_serializer=proto_dot_steelbeam__pb2.GetStockStatusRequest.SerializeToString,
                response_deserializer=proto_dot_steelbeam__pb2.GetStockStatusResponse.FromString,
                _registered_method=True)


class SteelBeamServiceServicer(object):
    """SteelBeam service definition
    """

    def GetBeams(self, request, context):
        """Get all steel beams
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBeam(self, request, context):
        """Get a specific steel beam by section designation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBeam(self, request, context):
        """Create a new steel beam
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockStatus(self, request, context):
        """Get stock status for a product
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SteelBeamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBeams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBeams,
                    request_deserializer=proto_dot_steelbeam__pb2.GetBeamsRequest.FromString,
                    response_serializer=proto_dot_steelbeam__pb2.GetBeamsResponse.SerializeToString,
            ),
            'GetBeam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBeam,
                    request_deserializer=proto_dot_steelbeam__pb2.GetBeamRequest.FromString,
                    response_serializer=proto_dot_steelbeam__pb2.GetBeamResponse.SerializeToString,
            ),
            'CreateBeam': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBeam,
                    request_deserializer=proto_dot_steelbeam__pb2.CreateBeamRequest.FromString,
                    response_serializer=proto_dot_steelbeam__pb2.CreateBeamResponse.SerializeToString,
            ),
            'GetStockStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockStatus,
                    request_deserializer=proto_dot_steelbeam__pb2.GetStockStatusRequest.FromString,
                    response_serializer=proto_dot_steelbeam__pb2.GetStockStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'steelbeam.SteelBeamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('steelbeam.SteelBeamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SteelBeamService(object):
    """SteelBeam service definition
    """

    @staticmethod
    def GetBeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/steelbeam.SteelBeamService/GetBeams',
            proto_dot_steelbeam__pb2.GetBeamsRequest.SerializeToString,
            proto_dot_steelbeam__pb2.GetBeamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/steelbeam.SteelBeamService/GetBeam',
            proto_dot_steelbeam__pb2.GetBeamRequest.SerializeToString,
            proto_dot_steelbeam__pb2.GetBeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/steelbeam.SteelBeamService/CreateBeam',
            proto_dot_steelbeam__pb2.CreateBeamRequest.SerializeToString,
            proto_dot_steelbeam__pb2.CreateBeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/steelbeam.SteelBeamService/GetStockStatus',
            proto_dot_steelbeam__pb2.GetStockStatusRequest.SerializeToString,
            proto_dot_steelbeam__pb2.GetStockStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
